name: Auto-approve

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions: read-all

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: github.actor == 'archy-rock3t-cloud' || github.actor == 'dependabot[bot]'
    steps:
      - uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: hmarr/auto-approve-action@8f929096a962e83ccdfa8afcf855f39f12d4dac7 # v4
        with:
          github-token: ${{ steps.app-token.outputs.token }}

  auto-approve-release:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'release/')
    steps:
      - uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2
        id: approver-token
        with:
          app-id: ${{ vars.APPROVER_APP_ID }}
          private-key: ${{ secrets.APPROVER_APP_PRIVATE_KEY }}

      - uses: hmarr/auto-approve-action@8f929096a962e83ccdfa8afcf855f39f12d4dac7 # v4
        with:
          github-token: ${{ steps.approver-token.outputs.token }}
